apiVersion: apps/v1
kind: DaemonSet
metadata:   
  name: my-daemonset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: amzon/cloudwatch-agent