apiVersion: v1
kind: Pod
metadata:
  name: nppod
  namespace: nginx
  labels:
    app: myapp
spec: 
  containers:
    - name: nginx-containers
      image: nginx:latest
      ports:
        - name: nginx-port
          containerPort: 80